// <auto-generated />
using System;
using Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngAce.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Criteria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("Entities.Models.ReadingExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Beginner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("manual");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Part 5");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReadingExercises", (string)null);
                });

            modelBuilder.Entity("Entities.Models.ReadingExerciseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReadingExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingExerciseResults", (string)null);
                });

            modelBuilder.Entity("Entities.Models.ReadingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingExerciseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingExerciseId");

                    b.ToTable("ReadingQuestions", (string)null);
                });

            modelBuilder.Entity("Entities.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("AverageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExercisesCompleted")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Platform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("XPEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudySessions", (string)null);
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Beginner");

                    b.Property<int>("StudyStreak")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudyTime")
                        .HasColumnType("int");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8831),
                            Email = "admin@englishmentorbuddy.com",
                            FullName = "Administrator",
                            IsActive = true,
                            LastActiveAt = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8817),
                            Level = "Advanced",
                            StudyStreak = 30,
                            TotalStudyTime = 1800,
                            TotalXP = 5000,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 12, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8844),
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsActive = true,
                            LastActiveAt = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8839),
                            Level = "Intermediate",
                            StudyStreak = 15,
                            TotalStudyTime = 900,
                            TotalXP = 2500,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 20, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8850),
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            IsActive = true,
                            LastActiveAt = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(8846),
                            Level = "Beginner",
                            StudyStreak = 7,
                            TotalStudyTime = 420,
                            TotalXP = 1200,
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("Entities.Models.UserProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageAccuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<TimeSpan>("AverageTimePerExercise")
                        .HasColumnType("time");

                    b.Property<int>("CompletedExercises")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("ListeningAccuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ListeningScore")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyGoal")
                        .HasColumnType("int");

                    b.Property<decimal>("ReadingAccuracy")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ReadingScore")
                        .HasColumnType("int");

                    b.Property<int>("SpeakingScore")
                        .HasColumnType("int");

                    b.Property<int>("TotalExercisesAvailable")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyGoal")
                        .HasColumnType("int");

                    b.Property<string>("WeeklyProgressData")
                        .HasColumnType("TEXT");

                    b.Property<int>("WritingScore")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserProgresses", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AverageAccuracy = 87.5m,
                            AverageTimePerExercise = new TimeSpan(0, 0, 0, 0, 0),
                            CompletedExercises = 25,
                            CurrentStreak = 30,
                            LastUpdated = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(9147),
                            ListeningAccuracy = 85.0m,
                            ListeningScore = 420,
                            MonthlyGoal = 40,
                            ReadingAccuracy = 90.0m,
                            ReadingScore = 450,
                            SpeakingScore = 170,
                            TotalExercisesAvailable = 50,
                            TotalScore = 870,
                            WeeklyGoal = 10,
                            WritingScore = 180
                        },
                        new
                        {
                            UserId = 2,
                            AverageAccuracy = 75.0m,
                            AverageTimePerExercise = new TimeSpan(0, 0, 0, 0, 0),
                            CompletedExercises = 15,
                            CurrentStreak = 15,
                            LastUpdated = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(9161),
                            ListeningAccuracy = 72.0m,
                            ListeningScore = 350,
                            MonthlyGoal = 30,
                            ReadingAccuracy = 78.0m,
                            ReadingScore = 380,
                            SpeakingScore = 140,
                            TotalExercisesAvailable = 50,
                            TotalScore = 730,
                            WeeklyGoal = 8,
                            WritingScore = 150
                        },
                        new
                        {
                            UserId = 3,
                            AverageAccuracy = 65.0m,
                            AverageTimePerExercise = new TimeSpan(0, 0, 0, 0, 0),
                            CompletedExercises = 8,
                            CurrentStreak = 7,
                            LastUpdated = new DateTime(2025, 10, 27, 21, 53, 7, 374, DateTimeKind.Utc).AddTicks(9167),
                            ListeningAccuracy = 62.0m,
                            ListeningScore = 280,
                            MonthlyGoal = 20,
                            ReadingAccuracy = 68.0m,
                            ReadingScore = 300,
                            SpeakingScore = 110,
                            TotalExercisesAvailable = 50,
                            TotalScore = 590,
                            WeeklyGoal = 5,
                            WritingScore = 120
                        });
                });

            modelBuilder.Entity("Entities.Models.Achievement", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.ReadingExerciseResult", b =>
                {
                    b.HasOne("Entities.Models.ReadingExercise", "ReadingExercise")
                        .WithMany("Results")
                        .HasForeignKey("ReadingExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("ExerciseResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingExercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.ReadingQuestion", b =>
                {
                    b.HasOne("Entities.Models.ReadingExercise", "ReadingExercise")
                        .WithMany("Questions")
                        .HasForeignKey("ReadingExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingExercise");
                });

            modelBuilder.Entity("Entities.Models.StudySession", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("StudySessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.UserProgress", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithOne("Progress")
                        .HasForeignKey("Entities.Models.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.ReadingExercise", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ExerciseResults");

                    b.Navigation("Progress");

                    b.Navigation("StudySessions");
                });
#pragma warning restore 612, 618
        }
    }
}
